# Documentation for the bundled datasets.

#' Count Data for 16S rRNA Sequences
#'
#' @name 16S
#' @rdname rRNA16S
#' @aliases rRNA16S
#' @aliases 16S
#' @aliases Alphaproteobacteria16S
#' @aliases Mollicutes16S
#' @docType data
#' @description This data set contains count data for 16S ribosomal RNA (rRNA) sequences for
#' the two phylogenetic classes Alphaproteobacteria and Mollicutes.
#' The counts for 30
#' sequences for each class were obtained by counting the occurrence of triplets
#' of nucleotides in windows of length 100 without any overlap. To
#' separate sequences a row of dummy count of \code{NA} is used.
#' @usage data("16S")
#' @format \code{Alphaproteobacteria16S} and \code{Mollicutes16S} are matrices
#'     with about 449 rows and 64 (number of possible triplets) columns.
#' @source The raw sequence information was obtained from the
#' National center for biotechnology information (NCBI) website at
#' http://www.ncbi.nih.gov/
#' @examples
#' data("16S")
#'
#' emm_mollicutes <- EMM("Kullback", threshold=0.1)
#' emm_alphaproteobacteria <- EMM("Kullback", threshold=0.1)
#'
#' # build with an added count of 1 for count smoothing
#' build(emm_mollicutes, Mollicutes16S + 1)
#' build(emm_alphaproteobacteria, Alphaproteobacteria16S + 1)
#'
#' plot(emm_mollicutes)
#' plot(emm_alphaproteobacteria)
#' @keywords datasets
NULL

#' Derwent Catchment Data
#'
#' @name Derwent
#' @rdname Derwent
#' @aliases Derwent
#' @docType data
#' @description Data set with flow readings (in cubic meter per second) for six catchments of
#' in the vicinity of the Derwent river in the northern UK.
#' The data was collected daily from November 1, 1971 -- January 31, 1977.
#' The catchments are Long Bridge, Matlock Bath, Chat Sworth,
#' What Stand Well, Ashford (Wye) and Wind Field Park (Amber).
#'
#' The owner of the data is the Ridings Area Office of the Environment
#' Agency North-East, UK.
#' @usage data(Derwent)
#' @format A matrix of size 1918 days times 6 catchments.
#' @source UK National River Flow Archive (NRFA),
#' \url{https://nrfa.ceh.ac.uk/}
#'
#' The owner of the data is the Ridings Area Office of the Environment
#' Agency North-East, UK.
#' @references Wikipedia, River Derwent, Yorkshire,
#' \url{https://en.wikipedia.org/wiki/River_Derwent,_Yorkshire}
#'
#' Wikipedia, River Wye, Derbyshire,
#' \url{https://en.wikipedia.org/wiki/River_Wye,_Derbyshire}
#'
#' Wikipedia, River Amber,
#' \url{https://en.wikipedia.org/wiki/River_Amber}
#' @examples
#' data(Derwent)
#'
#' i <- 1
#' plot(Derwent[,i], type="l", main=colnames(Derwent[i]), ylab="Gauged Flows")
#' @keywords datasets
NULL

#' Hypothetical Traffic Data Set for EMM
#'
#' @name EMMTraffic
#' @rdname EMMTraffic
#' @aliases EMMTraffic
#' @docType data
#' @description Each observation in this hypothetical data set is a vector of
#' seven values obtained from sensors located at specific
#' points on roads. Each sensor collects a count of the
#' number of vehicles which have crossed this sensor in
#' the preceding time interval.
#' @usage data(EMMTraffic)
#' @format A matrix with 12 observations (rows).
#' @references M.H. Dunham, Y. Meng, J. Huang (2004): Extensible Markov Model, In:
#' \emph{ICDM '04: Proceedings of the Fourth IEEE International
#' Conference on Data Mining,} pp. 371--374.
#' @examples
#' data(EMMTraffic)
#' EMMTraffic
#' @keywords datasets
NULL

#' Synthetic Data to Demonstrate EMMs
#'
#' @name EMMsim
#' @rdname EMMsim
#' @aliases EMMsim
#' @aliases EMMsim_train
#' @aliases EMMsim_test
#' @aliases EMMsim_sequence_train
#' @aliases EMMsim_sequence_test
#' @docType data
#' @description A simulated data set with four clusters in \eqn{R^2}. Each cluster is
#' represented by a bivariate normally distributed random variable.
#'
#' \eqn{\mu} are the coordinates of the means of the
#' distributions and \eqn{\Sigma} contains the covariance matrices.
#' Two data stream are created using a fixed sequence \eqn{<1,2,1,3,4>}
#' through
#' the four clusters. For the training data, the sequence is repeated 40 times
#' (200 data points) and for the test data five times (25 data points).
#'
#' The code to generate the data is shown in the Examples section below.
#' @usage data(EMMsim)
#' @format \code{EMMsim_train} and \code{EMMsim_test} are matrices containing the
#'     data.
#'
#' 	\code{EMMsim_sequence_train} and \code{EMMsim_sequence_test}
#'     contain the sequence of the data through the four clusters.
#' @examples data(EMMsim)
#' plot(EMMsim_train)
#' points(EMMsim_test, col = "red")
#'
#' ## the data was generated by
#' \dontrun{
#' set.seed(1234)
#'
#' ## simulated data
#' mu <- cbind(x = c(0, 0.2, 1, 0.9),
#'   y = c(0, 0.7, 1, 0.2))
#'
#' sd_rho <- cbind(
#'   x = c(0.2, 0.15, 0.05, 0.02),
#'   y = c(0.1, 0.04, 0.03, 0.05),
#'   rho = c(0, 0.7, 0.3,-0.4)
#' )
#'
#' Sigma <- lapply(
#'   1:nrow(sd_rho),
#'   FUN = function(i)
#'     rbind(
#'       c(sd_rho[i, "x"] ^ 2, sd_rho[i, "rho"] * sd_rho[i, "x"] * sd_rho[i, "y"]),
#'       c(sd_rho[i, "rho"] * sd_rho[i, "x"] * sd_rho[i, "y"], sd_rho[i, "y"] ^
#'           2)
#'     )
#' )
#'
#' sequence <- c(1, 2, 1, 3, 4)
#'
#' EMMsim_sequence_train <- rep(sequence, 40)
#' EMMsim_sequence_test <- rep(sequence, 5)
#'
#' library("MASS")
#' EMMsim_train <- t(sapply(
#'   EMMsim_sequence_train,
#'   FUN = function(i)
#'     mvrnorm(1, mu = mu[i, ], Sigma = Sigma[[i]])
#' ))
#'
#' EMMsim_test <- t(sapply(
#'   rep(EMMsim_sequence_test),
#'   FUN = function(i)
#'     mvrnorm(1, mu = mu[i, ], Sigma = Sigma[[i]])
#' ))
#' }
#' @keywords datasets
NULL
