#######################################################################
# rEMM - Extensible Markov Model (EMM) for Data Stream Clustering in R
# Copyright (C) 2011 Michael Hahsler
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#' Create a Synthetic Data Stream
#'
#' @name synthetic_stream
#' @rdname synthetic_stream
#' @aliases synthetic_stream
#' @description This function creates a synthetic data stream
#' with data points in roughly \eqn{[0, 1]^p} by choosing
#' points form k clusters following a sequence
#' through these clusters. Each cluster has a density function following a
#' d-dimensional normal distributions. In the test set outliers are introduced.
#' @param k number of clusters.
#' @param d dimensionality of data set.
#' @param n_subseq length of subsequence which will be repeat to create the data set.
#' @param p_transition probability that the next position in the subsequence will belong to a different cluster.
#' @param p_swap probability that two data points are swapped. This represents
#'   measurement errors (e.g., a data points arrive out of order) or that
#'   the data stream does not exactly follow the subsequence.
#' @param n_train size of training set (without outliers).
#' @param n_test size of test set (with outliers).
#' @param p_outlier probability that a data point is replaced by an outlier
#'   (a randomly chosen point in \eqn{[0,1]^p}).
#' @param rangeVar Used to create the random covariance matrices for the
#'   clusters. See \code{genPositiveDefMat()} in \pkg{clusterGeneration}
#'   for details.
#' @details The data generation process creates a data set consisting of \code{k}
#' clusters in
#' roughly \eqn{[0,1]^d}.  The data points for each cluster are be drawn from a
#' multivariate normal distribution given a random mean and a random
#' variance/covariance matrix for each cluster. The temporal aspect is modeled by
#' a fixed subsequence (of length \code{n_subseq}) through the k
#' clusters. In each step in the subsequence we
#' have a transition probability \code{p_transition} that the next data point
#' is in the same
#' cluster or in a randomly chosen other cluster, thus we can create slowly or
#' fast changing data.  For the complete sequence, the subsequence is repeated
#' to create \code{n_test}/\code{n_train} data points.
#' The data set is generated by drawing a data point from
#' the cluster corresponding to each position in the sequence. Outliers are
#' introduced by replacing data points in the data set with probability
#' \code{$p_outlier} by
#' randomly chosen data points in \eqn{[0,1]^d}.
#' Finally, to introduce imperfection
#' in the temporal sequence (e.g., because the data does not follow exactly a
#' repeating sequence or because observations do not arrive in the correct order),
#' we swap two consecutive observations with probability \code{p_swap}.
#' @return A list with the following elements:
#' \item{test}{ test data.}
#' \item{train}{ training data.}
#' \item{sequence_test}{ sequence of the test data points through the clusters.}
#' \item{sequence_train}{sequence of the training data points through the clusters.}
#' \item{swap_test}{index where points are swapped.}
#' \item{swap_train}{index where points are swapped.}
#' \item{outlier_position}{ logical vector for outliers in test data.}
#' \item{model}{ centers and covariance matrices for the clusters. }
#' @examples ## create only test data (with outliers)
#' ds <- synthetic_stream(n_train = 0)
#'
#' ## plot test data
#' plot(ds$test, pch = ds$sequence_test, col = "gray")
#' text(ds$model$mu[, 1], ds$model$mu[, 2], 1:10)
#'
#' ## mark outliers
#' points(ds$test[ds$outlier_position, ],
#'   pch = 3, lwd = 2, col = "red")
#' @keywords datagen
#' @export
synthetic_stream <-
  function(k = 10,
    d = 2,
    n_subseq = 100,
    p_transition = .5,
    p_swap = 0,
    n_train = 5000,
    n_test = 1000,
    p_outlier = .01,
    rangeVar = c(0, 0.005)) {
    test <- NA
    train <- NA
    outlier_position <- NA
    sequence_train <- NA
    sequence_test <- NA
    swap_train <- NA
    swap_test <- NA

    get_mu <- function(k)
      runif(k, min = .1, max = .9)
    get_outlier <- function(k)
      runif(k, min = 0, max = 1)

    mu <- replicate(d, get_mu(k))

    Sigma <- replicate(k,
      genPositiveDefMat("unifcorrmat",
        rangeVar = rangeVar, dim = d)$Sigma,
      simplify = FALSE)

    #subseq <- sample(1:k, replace=TRUE)
    subseq <- integer(n_subseq)
    subseq[1] <- 1L
    for (i in 2:n_subseq) {
      if (runif(1) < p_transition)
        subseq[i] <- sample(1:k, 1)
      else
        subseq[i] <- subseq[i - 1]
    }

    model <- list(
      k = k,
      d = d,
      mu = mu,
      Sigma = Sigma,
      subseq = subseq
    )

    if (n_train > 0) {
      sequence_train <- rep(subseq, n_train / n_subseq)


      ## randomly mess up sequence missing
      if (p_swap > 0) {
        swap_train <- which(runif(n_train - 1) < p_swap) + 1L
        for (i in swap_train) {
          sequence_train[(i - 1):i] <-
            rev(sequence_train[(i - 1):i])
        }
        #tmp <- sequence_train[swap_train]
        #sequence_train[swap_train] <- sequence_train[swap_train-1]
        #sequence_train[swap_train-1] <- tmp
      }

      train <- t(sapply(
        sequence_train,
        FUN = function(i)
          mvrnorm(1, mu = mu[i, ], Sigma = Sigma[[i]])
      ))
    }

    if (n_test > 0) {
      sequence_test <- rep(subseq, n_test / n_subseq)

      ## randomly mess up sequence missing
      if (p_swap > 0) {
        swap_test <- which(runif(n_test - 1) < p_swap) + 1L
        for (i in swap_test) {
          sequence_test[(i - 1):i] <-
            rev(sequence_test[(i - 1):i])
        }
        #swap_test <- which(runif(n_test-1)<p_swap)+1L
        #tmp <- sequence_test[swap_test]
        #sequence_test[swap_test] <- sequence_test[swap_test-1]
        #sequence_test[swap_test-1] <- tmp
      }

      test <- t(sapply(
        sequence_test,
        FUN = function(i)
          mvrnorm(1, mu = mu[i, ], Sigma = Sigma[[i]])
      ))

      ## outliers are random points
      outlier_position <- runif(n_test) < p_outlier
      n_outliers <- sum(outlier_position)
      if (d > 1)
        test[outlier_position,] <- replicate(d,
          get_outlier(n_outliers))
      else
        test[outlier_position] <- get_outlier(n_outliers)

    }

    list(
      test = test,
      train = train,
      sequence_test = sequence_test,
      sequence_train = sequence_train,
      swap_test = swap_test,
      swap_train = swap_train,
      outlier_position = outlier_position,
      model = model
    )
  }
